### ISSUE TITLE
aarch64 linux: `dup2_stdout(stdout())` closes stdout

### ISSUE THREAD

**Issue by 0f-0b** [bytecodealliance/rustix#1067]
This program panics with a “Bad file descriptor” error on line 2 because stdout is closed on line 1.

```rs
use rustix::io::fcntl_getfd;
use rustix::stdio::{dup2_stdout, stdout};

fn main() {
    let _ = dup2_stdout(stdout()); // 1
    fcntl_getfd(stdout()).unwrap(); // 2
}
```

```toml
[dependencies]
rustix = { version = "0.38.34", features = ["stdio"] }
```
